# Generated by Django 5.1.6 on 2025-02-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='diet_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good')], default='Average', max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='exercise_frequency',
            field=models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], default='Sometimes', max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='social_support',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=50),
        ),
    ]
