# Generated by Django 5.1.6 on 2025-02-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_mentalhealthprogress_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthprogress',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='mentalhealthprogress',
            name='progress_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentalhealthprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
