# Generated by Django 5.1.6 on 2025-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_remove_userprofile_user_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
