# Generated by Django 5.1.6 on 2025-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatsession_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
