# Generated by Django 5.1.6 on 2025-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_chatsession_options_chatsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='progress_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='diet_quality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='exercise_frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='mood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='social_support',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='stress_level',
            field=models.IntegerField(),
        ),
    ]
