# Generated by Django 5.1.6 on 2025-02-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_chatmessage_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
