# Generated by Django 5.1.6 on 2025-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_chatsession_sentiment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chat_sessions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='questionnaire_completed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress_score',
            field=models.FloatField(default=0.0),
        ),
    ]
