# Generated by Django 5.1.6 on 2025-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_questionnaire_stress_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sentiment_score',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='exercise_frequency',
            field=models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly'), ('Daily', 'Daily')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='stress_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=8),
        ),
    ]
