# Generated by Django 5.1.6 on 2025-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_remove_chatmessage_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
