# Generated by Django 5.1.6 on 2025-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_userprofile_questionnaire_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
