# Generated by Django 5.1.6 on 2025-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_chatmessage_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progress_score',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
